---
- name: test                  # Название плейбука
  gather_facts: false         # Отключаем сбор фактов
  hosts: webservers           # Целевая группа хостов
  vars:                       # Переменные
    ansible_ssh_user: user    # Пользователь для SSH
  become: yes                 # Включено повышение привилегий

  pre_tasks:                  # Предварительные задачи
    - name: Validating the ssh port is open
      wait_for:               # Ожидание доступности порта
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        port: 22              # Порт SSH
        delay: 5              # Задержка между проверками
        timeout: 300          # Максимальное время ожидания
        state: started        # Ожидание открытия
        search_regex: OpenSSH # Проверка ответа SSH

  tasks:                      # Основные задачи
    - name: create test file
      copy:                   # Копирование файла
        dest: /tmp/test       # Путь назначения
        content: "success"    # Содержимое файла
